### ISSUE TITLE
Elastic Search Java API : migrate from old TransportClient to Java High Level REST Client

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-server#136]
In gitlab by @sfalquier on Dec 27, 2017, 10:01

TransportClient is about to be deprecated : https://www.elastic.co/guide/en/elasticsearch/client/java-api/current/java-api.html

Wait for more Java High Level REST Client completeness : https://github.com/elastic/elasticsearch/issues/27205

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sfalquier on Dec 27, 2017, 10:01

added ~2424198 label

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sfalquier on Dec 27, 2017, 10:59

removed ~2424198 label

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sfalquier on Dec 27, 2017, 11:00

changed the description

**Comment by MohamedHamouGisaia** [comment]
Fixed in #612 
Released in v12.7.6
