### ISSUE TITLE
Add a new API that tags the result of a query

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-server#140]
In gitlab by @MohamedHamouGisaia on Jan 4, 2018, 14:01

**Comment by elouanKeryell-Even** [comment]
In gitlab by @MohamedHamouGisaia on Jan 4, 2018, 14:01

added ~2329926 label

**Comment by MohamedHamouGisaia** [comment]
Fixed in #243 PR
