### ISSUE TITLE
Add cardinality aggregation to ARLAS server

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-server#148]
In gitlab by @sylvaingaudan on Feb 7, 2018, 07:08

Add cardinality aggregation to ARLAS server: 
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html

Note for high cardinality fields:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_pre_computed_hashes

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sylvaingaudan on Feb 7, 2018, 17:17

added ~2329926 label

**Comment by MohamedHamouGisaia** [comment]
This aggregation exists already
