### ISSUE TITLE
Enable/Disable services

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-server#149]
In gitlab by @sylvaingaudan on Feb 8, 2018, 07:27

It should be possible to start ARLAS Server with some services enabled and other disabled.
For instance
/explore enabled
/collections disabled
/ogc/wfs disabled

This should be done in the configuration file of ARLAS and also exposed as docker environment variables

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sfalquier on Feb 9, 2018, 15:27

mentioned in commit 48dd2577e0e7637beeae2c2df467663cb400a9c8

**Comment by sfalquier** [comment]
Already merged.
