### ISSUE TITLE
Implement Simple WFS with simple Feature

### ISSUE THREAD

**Issue by mbarbet** [gisaia/ARLAS-server#168]
Implement OGC simple WFS with simple feature.
A simple feature has:
- a point geometry from md arlas centroid
- an ID from md arlas id 
-  a timestamp from md arlas timestamp.

Method available:
- GetCapabilities
- DescribeFeatureType
- ListStoredQueries
- DescribeStoredQueries
- GetFeature for  request by ID stored query

**Comment by sfalquier** [comment]
merged with PR #154
