### ISSUE TITLE
Selection disappear in powerbars

### ISSUE THREAD

**Issue by WilliGautier** [gisaia/ARLAS-server#268]
Before unselection
![image](https://user-images.githubusercontent.com/36915512/39258754-0ae4534e-48b5-11e8-9041-be52b78b5968.png)

After unselection
![image](https://user-images.githubusercontent.com/36915512/39258818-357e8782-48b5-11e8-8155-1af9d5783ea7.png)

The selection is still ok but it doesn't appear 

@MohamedHamouGisaia

**Comment by mbarbet** [comment]
It's not a server problem, it's  a WUI problem. 
Please re-open this issue in the ARLAS-wui repo
