### ISSUE TITLE
Useless OpensearchConfiguration removed

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-server#324]
The ARLAS Server configuration contains an unused property "opensearch":
- io/arlas/server/app/ArlasServerConfiguration.java
- conf/configuration.yaml
- docs/arlas-server-configuration.md

Those references to the unused OpensearchConfiguration must be removed.

**Comment by MohamedHamouGisaia** [comment]
It is used in OpenSearchDescriptorService
