### ISSUE TITLE
Proper exception management in CheckParams.checkBbox

### ISSUE THREAD

**Issue by laurent-thiebaud-gisaia** [gisaia/ARLAS-server#351]
To repeat:
Send a count request with a a pwithin and incorrect values, eg:

        `Count count = new Count();
        count.filter = new Filter();

        MultiValueFilter<String> multiValue = new MultiValueFilter<>();
        ArrayList<MultiValueFilter<String>> pwithin = new ArrayList<>();
        count.filter.pwithin = pwithin;
        pwithin.add(multiValue);

        multiValue.add("10.42055");
        multiValue.add("6.960925");
        multiValue.add("1.146275");
        multiValue.add("30.4537");`

Then check this object with CheckParams.checkBbox(count)

It crashes then on line:
`if ((tlbr.length != 4 || !isBboxLatLonInCorrectRanges(tlbr) || tlbr[3] <= tlbr[1]) && tlbr[0] != tlbr[2]) {`

The problem is that  tlbr[2] throws `ArrayOutOfBoundException`, whereas it should throw a `InvalidParameterException("Invalid BBOX");`

**Comment by mbarbet** [comment]
this line `if ((tlbr.length != 4 || !isBboxLatLonInCorrectRanges(tlbr) || tlbr[3] <= tlbr[1]) && tlbr[0] != tlbr[2])`
does not exist anymore in last tag of Arlas
Update your versoin
