### ISSUE TITLE
testGwithinFilter tests fails when bumping Elasticsearch to 6.6.1 

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-server#411]
Starting from Elasticsearch 6.6.0, geo_shapes are indexed in BKD trees.

With this new method, a false-positive is detected in our ITs: one of the IT fails.

# The test that fails
In our dataset for ITs, we assert that the query bellow returns 42 hits (*all hits which geometries are not within at least one of the 2 polygons*): 
```
  "filter": {
    "notgwithin": [
         [ "POLYGON((180 90,-180 90,-180 -80,100 -80,100 -70,180 -70,180 90))", 
           "POLYGON((180 90,-180 90,-180 -90,160 -90,160 -70,180 -70,180 90))"
         ]
    ]
  }
```

But with BKD tree indexation, this same query returns 43 hits.
# The false-positive hit
The coordinates of the additional hit (in red) are `[  [ 99, -69], [101, -69], [101, -71 ],	[99, -71 ], [ 99, -69 ]  ]`
![image](https://user-images.githubusercontent.com/26741864/53744777-fb650500-3e9d-11e9-9af8-435522755c35.png)

In quadree indexations, the red polygon was considered as within the polygon1. This is due to the precision of quadtree which is 50m by default

# Fix 
In order to make the results of tests identical between the two methods of indexing
- Specify and increase the indexation precision (it will make ITs slower as indexation will take more time) => This supposes we index the geo_shapes of the dataset with quadtree method
OR
- Change the coordinates of Polygon1 to make the red polygon within it => This supposes we index the geo_shapes of the dataset with BKD-tree

**Comment by MohamedHamouGisaia** [comment]
Ping @mbarbet @sfalquier @sylvaingaudan

**Comment by alainbodiguel** [comment]
See PR #409
