### ISSUE TITLE
Problem with "size" param support in geohash aggregation

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-server#42]
In gitlab by @sfalquier on May 3, 2017, 14:34

A _geoaggregation request makes different values for features.properties.count of a given point when using different "size" parameter.

For example :

- geohash:centroid:interval-1
   {
      "type": "Feature",
      "properties": {
        "geohash": "s00000000000",
        "elements": null,
        "count": 25
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          0,
          0
        ]
      }
    }
...

- geohash:centroid:interval-1:size-1
    {
      "type": "Feature",
      "properties": {
        "geohash": "s00000000000",
        "elements": null,
        "count": 23
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          0,
          0
        ]
      }
    }

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sfalquier on May 3, 2017, 14:39

made the issue confidential

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sylvaingaudan on Jul 17, 2017, 15:06

added ~2291850 label

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sfalquier on Jul 21, 2017, 11:24

added ~1918908 label

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sfalquier on Jul 21, 2017, 11:24

removed ~1918908 label

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sylvaingaudan on Sep 11, 2017, 11:48

changed milestone to %13

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sfalquier on Sep 15, 2017, 11:00

removed milestone

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sylvaingaudan on Feb 7, 2018, 17:10

added ~2424198 label

**Comment by elouanKeryell-Even** [comment]
In gitlab by @sylvaingaudan on Feb 7, 2018, 17:10

removed ~2424198 label

**Comment by alainbodiguel** [comment]
No longer an issue as geohash does not support the size parameter.
{
  "status": 501,
  "message": "Size is not implemented for geohash/geotile.",
  "error": "io.arlas.server.core.exceptions.NotImplementedException"
}
