### ISSUE TITLE
_(geo)aggregate :  Add geotile aggregation type

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-server#449]
As a user of ARLAS-server `_aggregate` service

I want to be able to aggregate geo-points using a `map tile` grid *({zoom}/{x}/{y})* with a large precision range (larger than the geohash grid aggregation precision range)

in order to smooth the precision changes while zooming in (in a map client for example)

According to the documentation 
https://www.elastic.co/guide/en/elasticsearch/reference/7.11/search-aggregations-bucket-geotilegrid-aggregation.html

Technically this means :
- [x] new aggregation type **geotile**
  - datehistogram
  - histogram
  - term
  - geohash
  - **geotile**

- [x] new endpoint `@Path("{collection}/_geoaggregate/{z}/{x}/{y}")
   - so we need to transform {z}/{x}/{y} EPSG 3857 tiles to a bounding box as top_left and bottom_right. (same behaviour of the endpoint `@Path("{collection}/_geoaggregate/{geohash}")`)
- [x] For this new agg type, we need to pass a precision in the `agg` query param, in the `interval` attribute (default value `z+3` if not specified)
   - this precision corresponds to zoom level of the aggregation, that should be larger than or equal to {z} in the path param
   - the maximum difference between the precision and {z} in the path param is **6**
   - If we want a difference of 7 we need to split the  bbox resulting from the {z}/{x}/{y} tile into 4 similar bboxes the same way we did #656 
- [x] How to handle returned geometries by the ES aggregation ?
  - The response of ES is 
```
   "aggregations": {
    "large-grid": {
      "buckets": [
        {
          "key": "8/131/84",
          "doc_count": 3
        },
        {
          "key": "8/129/88",
          "doc_count": 2
        },
        {
          "key": "8/131/85",
          "doc_count": 1
        }
      ]
    }
    }
```
We need to transform the `"key"` to a geometry. The geometry to return is to be specified in `aggregated_geometries` subparam of the `agg` param.

For now `aggregated_geometries` have four possible values
- geohash
- geohash_center
- centroid
- bbox

- [x] First thing we need to do, is replace 
`geohash` => `tile`
`geohash_center` => `tile_center`
in order to be generic to the `**geotile**` and `**geohash**`

- [x] Update documentation
- [ ] Integration tests

**Comment by alainbodiguel** [comment]
New agg type "GEOTILES" to add.
