### ISSUE TITLE
SWAGGER Documentation is not up to date

### ISSUE THREAD

**Issue by sylvaingaudan** [gisaia/ARLAS-server#684]
endpoint `/explore/{collection}/_geoaggregate/{geohash}` has issues on the agg parameter format
   - contains in the format the field `fetcbGeometry` which does not exist anymore
   - does not contain `raw_geometries`
   - does not contain `fetch_hits`
   - does not contain `aggregated_geometries`

endpoint `/explore/{collection}/_geoaggregate` has issues on the agg parameter format
   - contains in the format the field `fetcbGeometry` which does not exist anymore
   - does not contain `raw_geometries`
   - does not contain `fetch_hits`
   - does not contain `aggregated_geometries`

endpoint `/explore/{collection}/_aggregate` has issues on the agg parameter format
   - does not contain `raw_geometries`
   - does not contain `fetch_hits`
   - does not contain `aggregated_geometries`

Also, the documentation about `aggregated_geometries` and `raw_geometries` states
> What it does: Allows to specify a list of aggregated forms of geometries that represent the bucket.
> What it does: Allows to specify a list of raw geometries provided by hits that represent the bucket and thata are elected by a sort

but it does not explain why it is usefull to list those fields: is it to fetch the geometries?

**Comment by alainbodiguel** [comment]
It was fixed in a previous release.
