### ISSUE TITLE
Support multi-collection in `partition-filter`

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-server#749]

**Comment by alainbodiguel** [comment]
Proposed implementation is to pass the partition filter as a map <collection name, filter>, e.g.:
``` partition-filter: {"mycollection1": {"f":[[{"field":"city","op":"eq","value":"Bordeaux"}]]}}```
The previous format is still supported and is a fallback in case the partition filter cannot be parsed as the new format, e.g.:
```partition-filter: {"f":[[{"field":"city","op":"eq","value":"Bordeaux"}]]}```
