### ISSUE TITLE
Issues with the python API

### ISSUE THREAD

**Issue by QuCMGisaia** [gisaia/ARLAS-server#789]
- [ ] When creating a client API, it is not possible to specify a host to the class Configuration, which is needed
- [ ] The default host for Configuration (localhost/arlas) returns an error
- [ ] It should be stated that agg needs to be given as a list, because of how it is tagged as multi in the API requests
- [ ] Aggregation does not have a "collect_fct" attribute
- [ ] The to_str function of filters and aggregation should be used to be able to launch a query, but the returned object does not have the right format

**Comment by alainbodiguel** [comment]
Python API no longer generated.
