### ISSUE TITLE
NPE on stac collection endpoint if no data in the collection

### ISSUE THREAD

**Issue by mbarbet** [gisaia/ARLAS-server#840]
`WARN  [2022-10-27 07:40:16,618] org.eclipse.jetty.server.HttpChannel: /arlas-dinamis/arlas/stac/collections/SPOT1
! java.lang.NullPointerException: Cannot invoke "org.geojson.Polygon.getCoordinates()" because "polygon" is null
! at io.arlas.server.stac.api.StacRESTService.getBbox(StacRESTService.java:423)
! at io.arlas.server.stac.api.StacRESTService.getSpatialExtent(StacRESTService.java:418)
! at io.arlas.server.stac.api.StacRESTService.getCollection(StacRESTService.java:164)
! at io.arlas.server.stac.api.StacCollectionsRESTService.describeCollection(StacCollectionsRESTService.java:134)`

Please, fix this bug in develop and in the current 22.X.X version

**Comment by alainbodiguel** [comment]
Fixed in #827 
Cherry picked in https://github.com/gisaia/ARLAS-server/tree/tag/22.0.1
