### ISSUE TITLE
swagger2markdown documentation is generated in every sub-module of ARLAS-server

### ISSUE THREAD

**Issue by MohamedHamouGisaia** [gisaia/ARLAS-server#894]
- https://github.com/gisaia/ARLAS-server/tree/develop/arlas-core/docs/api
- https://github.com/gisaia/ARLAS-server/tree/develop/arlas-rest/docs/api

They all have the same content.
- [ ] investigate how they are pushed there
- [ ] should we have a dedicated api doc for each sub-module
- [ ] remove them otherwise

**Comment by alainbodiguel** [comment]
No longer a problem after #954
